import type { DashboardData } from "@/lib/fleet/types";

const now = new Date();

export const MOCK_DASHBOARD_DATA: DashboardData = {
  fleetHealth: {
    total: 20,
    operational: 18,
    occupied: 11,
    inService: 2,
    percentage: 90,
  },
  costSeries: [
    { monthKey: "2025-10", monthLabel: "Lis", fuelCost: 4680, serviceCost: 1730 },
    { monthKey: "2025-11", monthLabel: "Stu", fuelCost: 5025, serviceCost: 2190 },
    { monthKey: "2025-12", monthLabel: "Pro", fuelCost: 4810, serviceCost: 1935 },
    { monthKey: "2026-01", monthLabel: "Sij", fuelCost: 5265, serviceCost: 2470 },
    { monthKey: "2026-02", monthLabel: "Velj", fuelCost: 5120, serviceCost: 2010 },
    { monthKey: "2026-03", monthLabel: "Ožu", fuelCost: 5485, serviceCost: 2890 },
  ],
  criticalAlerts: [
    {
      id: "registracija-1",
      type: "registracija",
      title: "Registracija ističe uskoro",
      description: "Vozilo M23-A-123 ističe za 6 dana.",
      severity: "kriticno",
      createdAtIso: now.toISOString(),
    },
    {
      id: "servis-1",
      type: "servis",
      title: "Prekoračen mali servis",
      description: "Škoda Octavia je 320 km preko intervala malog servisa.",
      severity: "upozorenje",
      createdAtIso: now.toISOString(),
    },
    {
      id: "kvar-1",
      type: "kvar",
      title: "Nova prijava kvara",
      description: "VW Polo prijavljen kvar: trešnja pri kočenju.",
      severity: "kriticno",
      createdAtIso: now.toISOString(),
    },
  ],
  criticalAlertCount: 2,
  vehicles: [
    {
      id: 1,
      make: "Volkswagen",
      model: "Polo",
      plate: "M23-A-123",
      km: 142345,
      fuelCapacity: 45,
      fuelTypeLabel: "Benzin",
      smallServiceDueKm: 380,
      largeServiceDueKm: 22700,
      serviceDueKm: 380,
      serviceDueType: "none",
      serviceDueLabel: "380 km do malog servisa",
      serviceProgressIntervalKm: 15000,
      isServiceDue: false,
      status: "Zauzeto",
      registrationExpiryDays: 6,
      registrationExpiryDateIso: now.toISOString().slice(0, 10),
      openFaultCount: 1,
      isActive: true,
      deactivationReason: null,
      vin: "WVWZZZ1JZXW000001",
      acquisitionValue: null,
      productionYear: null,
      registrationCity: null,
      locationCity: null,
      lastSmallServiceDate: null,
      lastSmallServiceKm: null,
      lastLargeServiceDate: null,
      lastLargeServiceKm: null,
    },
    {
      id: 2,
      make: "Škoda",
      model: "Octavia",
      plate: "M24-B-982",
      km: 230112,
      fuelCapacity: 50,
      fuelTypeLabel: "Dizel",
      smallServiceDueKm: -320,
      largeServiceDueKm: 18450,
      serviceDueKm: -320,
      serviceDueType: "mali",
      serviceDueLabel: "mali servis kasni 320 km",
      serviceProgressIntervalKm: 15000,
      isServiceDue: true,
      status: "Slobodno",
      registrationExpiryDays: 12,
      registrationExpiryDateIso: now.toISOString().slice(0, 10),
      openFaultCount: 0,
      isActive: true,
      deactivationReason: null,
      vin: "TMBZZZ1ZXVW000002",
      acquisitionValue: null,
      productionYear: null,
      registrationCity: null,
      locationCity: null,
      lastSmallServiceDate: null,
      lastSmallServiceKm: null,
      lastLargeServiceDate: null,
      lastLargeServiceKm: null,
    },
    {
      id: 3,
      make: "Renault",
      model: "Clio",
      plate: "M11-C-445",
      km: 101220,
      fuelCapacity: 42,
      fuelTypeLabel: "Benzin",
      smallServiceDueKm: 2140,
      largeServiceDueKm: 46890,
      serviceDueKm: 2140,
      serviceDueType: "none",
      serviceDueLabel: "2.140 km do malog servisa",
      serviceProgressIntervalKm: 15000,
      isServiceDue: false,
      status: "Na servisu",
      registrationExpiryDays: 43,
      registrationExpiryDateIso: now.toISOString().slice(0, 10),
      openFaultCount: 1,
      isActive: true,
      deactivationReason: null,
      vin: "VF15R000000000003",
      acquisitionValue: null,
      productionYear: null,
      registrationCity: null,
      locationCity: null,
      lastSmallServiceDate: null,
      lastSmallServiceKm: null,
      lastLargeServiceDate: null,
      lastLargeServiceKm: null,
    },
    {
      id: 4,
      make: "Ford",
      model: "Transit",
      plate: "M08-D-301",
      km: 287510,
      fuelCapacity: 72,
      fuelTypeLabel: "Dizel",
      smallServiceDueKm: 965,
      largeServiceDueKm: 12540,
      serviceDueKm: 965,
      serviceDueType: "none",
      serviceDueLabel: "965 km do malog servisa",
      serviceProgressIntervalKm: 15000,
      isServiceDue: false,
      status: "Zauzeto",
      registrationExpiryDays: 9,
      registrationExpiryDateIso: now.toISOString().slice(0, 10),
      openFaultCount: 1,
      isActive: true,
      deactivationReason: null,
      vin: "WF0XXXTTGX0000004",
      acquisitionValue: null,
      productionYear: null,
      registrationCity: null,
      locationCity: null,
      lastSmallServiceDate: null,
      lastSmallServiceKm: null,
      lastLargeServiceDate: null,
      lastLargeServiceKm: null,
    },
  ],
  activeFaultCount: 3,
  lastUpdatedIso: now.toISOString(),
  isUsingFallbackData: true,
};
